### ISSUE TITLE
Reverse geocoding problem

### ISSUE THREAD

**Issue by remedyyy** [AtlisInc/Nominatim-API#5]
Hello.
I am trying to get longitude and latitude values.But for every different input longitude and latitude outputs are being same.For  latitude =  51.3258094 and for longitude =  11.3400106. What am I doing wrong?
Thank you very much.Here is the code:

public class ReverseGeocoding{
import com.atlis.location.model.impl.Address;
import com.atlis.location.model.impl.MapPoint;
import com.atlis.location.nominatim.NominatimAPI;

import java.util.Arrays;
import java.util.List;
List<String> cities = Arrays.asList("New York", "Berlin", "Jerusalem", "Tel Aviv", "Rome");

        for (String city : cities) {
            Address address = new Address();
            address.setCity(city);
            String endpointUrl = "https://nominatim.openstreetmap.org/";
            MapPoint mapPoint = NominatimAPI.with(endpointUrl).getMapPointFromAddress(address, 900);
}
}

**Comment by michaelassraf** [comment]
look like your precision is too high - 900.
